[package]
name = "adapter-out-db-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
ai-core = { path = "../ai-core" }
tokio.workspace = true
tokio-postgres = "0.7.13"
deadpool-postgres = { version = "0.14.1", features = ["rt_tokio_1", "serde"] }
deadpool = { version = "0.12.3", features = ["managed"] }
refinery = { version = "0.8.16", features = ["tokio-postgres"] }
anyhow.workspace = true
thiserror.workspace = true
dotenvy.workspace = true
config.workspace = true
serde.workspace = true
uuid.workspace = true
postgres-types = { version = "0.2.9", features = ["with-time-0_3", "with-uuid-1"] }
tracing.workspace = true
time.workspace = true
url.workspace = true
indexmap.workspace = true